apiVersion: v1
kind: LimitRange
metadata:
  name: example
spec:
  limits:
  - type: Pod
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 1                                   # Maximum CPU and memory all the pod’s containers can request (and limit)
      memory: 1Gi
  - type: Container
    defaultRequest:                            # Default requests for CPU and memory that will be applied to containers that don’t specify them explicitly
      cpu: 100m
      memory: 10Mi
    default:                                   # Default limits for containers that don’t specify them 
      cpu: 200m
      memory: 100Mi
    min:
      cpu: 50m
      memory: 5Mi
    max:
      cpu: 1
      memory: 1Gi
    maxLimitRequestRatio:                      # ratio of requests to limits for each resource
      cpu: 4
      memory: 10
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 10Gi
